server:
  port: 0

spring:
  application:
    name: Administrator
  ## Spring DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false&serverTimezone=UTC
    username: root
    password: santy012
  jpa:
    ## Hibernate Properties
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddlAuto: update
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
