server:
  port: 8800

spring:
  application:
    name: gateway

zuul:
  ignored-services: "*"
  routes:
    administratorClient:
      serviceId: Administrator
      path: /administrator/**
    librarianClient:
      serviceId: Librarian
      path: /librarian/**
    borrowerClient:
      serviceId: Borrower
      path: /borrower/**

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  eureka:
    enabled: true